package com.pm.patientservice.mapper;

import com.pm.patientservice.dto.PatientRequestDTO;
import com.pm.patientservice.dto.PatientResponseDTO;
import com.pm.patientservice.model.Patient;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;




@Mapper(
        componentModel = "spring",
        unmappedTargetPolicy = org.mapstruct.ReportingPolicy.IGNORE // Removes warnings for all fields at once
) // Allows you to implement a mapper via @Autowired/final
public interface PatientMapper {

    /**
     * Converts Entity to DTO for API responses.
     * MapStruct automatically handles UUID to String conversion if names match.
     */
    PatientResponseDTO toDTO(Patient patient);

    /**
     * Converts DTO to Entity for creating new patient records.
     * ID is ignored because it is generated by the database/service.
     */
    @Mapping(target = "id", ignore = true)
    Patient toModel(PatientRequestDTO patientRequestDTO);

    /**
     * Updates an existing Entity with values from a DTO.
     * ID is ignored to prevent accidental overwriting of the primary key.
     */
    @Mapping(target = "id", ignore = true) // Don't overwrite the ID
    void updatePatientFromDto(PatientRequestDTO dto, @MappingTarget Patient entity);

}